### ISSUE TITLE
Use rust-url?

### ISSUE THREAD

**Issue by pyfisch** [tarcieri/pkixnames#1]
Hyper uses typed URLs (or should do so, relative URLs are not supported by rust-url) so it would be good if pkixnames would accept typed domain namrs, it may also make parsing easier I think.

**Comment by tarcieri** [comment]
This library doesn't operate on URLs per se. I was in fact thinking of going the opposite direction, at least for the core, and modeling everything in terms of `Vec<u8>s`, and perhaps adding some sort of `PresentedIdentifier`/`ReferenceIdentifier` wrappers around Vec<u8s>

**Comment by pyfisch** [comment]
Sounds reasonable.
